format_version: 10
pipelines:
 master-ami:
  group: TerraformGroup
  label_template: ${COUNT}
  lock_behavior: none
  display_order: -1
  materials:
    git-3caedef:
      git: https://github.com/s-devops-i2/master-ami.git
      shallow_clone: false
      auto_update: true
      branch: main
  secure_variables:
    TF_VAR_vault_token: AES:Sm/GySenrKRWu0QDKWH/IQ==:2QCFewXX/NGtNjBc5zY6ZaB/cT+pIGPOVjobBcXIveQ=
  stages:
    - CREATE:
        environment_variables:
          env: dev
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          terraform-apply:
            timeout: 0
            tasks:
              - exec: {command: terraform, arguments: ["init"],run_if: passed}
              - exec: {command: terraform, arguments: ["apply", "-auto-approve" ],run_if: passed}

    - DELETE:
        environment_variables:
          env: dev
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          terraform-apply:
            timeout: 0
            tasks:
              - exec: { command: terraform, arguments: [ "init" ],run_if: passed }
              - exec: { command: terraform, arguments: [ "state", "rm","aws_ami_from_instance.ami"],run_if: passed }
              - exec: { command: terraform, arguments: [ "destroy", "-auto-approve" ],run_if: passed }


